---

- hosts: all
  remote_user: root

  tasks: 

    - name: Upgrade Debian
      apt: 
        update_cache: yes
        upgrade: yes

    - name: Get parity
      get_url:
        url: https://releases.parity.io/ethereum/v2.7.2/x86_64-unknown-linux-gnu/parity
        dest: /var/tmp/parity
        validate_certs: no

    - name: Install parity
      copy: 
        src: /var/tmp/parity
        dest: /usr/local/bin/parity
        force: yes
        mode: '0755'
        remote_src: yes
